name: dio_http_cache
description: http cache lib for Flutter dio like RxCache.It use sqflite as disk cache,and google/quiver-dart/LRU strategy as memory cache.
version: 0.3.0
authors:
  - Hurshi <ihsruh@gmail.com>
  - Eric Kok <erickok@gmail.com>
homepage: https://github.com/hurshi/dio-http-cache

environment:
  sdk: '>=2.12.0'

dependencies:
  crypto: any
  dio: any
  flutter:
    sdk: flutter
  json_serializable: any
  json_annotation: any
  path: any
  quiver: any
  sqflite: any

dev_dependencies:
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter

flutter:
  module:
    androidX: true
